version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: payment_db
    environment:
      POSTGRES_USER: user_payment
      POSTGRES_PASSWORD: pass_payment
      POSTGRES_DB: db_payment
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d # Jalankan SQL otomatis saat container dibuat