version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: payment_db
    environment:
      POSTGRES_USER: user_payment
      POSTGRES_PASSWORD: pass_payment
      POSTGRES_DB: db_payment
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: payment_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user_payment
      DB_PASSWORD: pass_payment
      DB_NAME: db_payment
    depends_on:
      - db
